name: Update Baseball Data

on:
  schedule:
    # Run daily at 6 AM UTC (2 AM EST)
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install
    
    - name: Update data
      run: |
        cd pitch_prospector
        python -c "
        from indexing.auto_refresh_pitch_index import auto_refresh_pitch_index
        auto_refresh_pitch_index()
        "
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add pitch_prospector/data/
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update baseball data $(date +%Y-%m-%d)"
        git push 